import Head from 'next/head'
import { BsToggle2On } from 'react-icons/bs';
import {AiFillLinkedin, AiFillGithub} from 'react-icons/ai';
import Image from 'next/image';
// import deved from "../public/dev-ed-wave.png"
// import niyo from '../public/niyo.png'
import raiyan from '../public/Raiyan.jpg'

export default function Home() {
  return (
    <>
      <Head>
        <title>Raiyan Khalil Shuvo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-myGunMetal text-white px-10 lg:max-w-[70%] lg:mx-auto pb-12 md:px-20 lg:px-15 font-burtons'>
        <section className=''>
          <nav className='py-10 mb-8 flex justify-between'>
            <h1 className='text-xl font-burtons'>Raiyan Khalil Shuvo</h1>
            <ul className='flex items-center'>
              {/* <li>
                <BsToggle2On className='cursor-pointer text-xl'/>
              </li> */}
              <li>
                <a className='bg-myCoral text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-4xl py-2 text-myCoral font-medium md:text-6xl'>Raiyan Khalil Shuvo</h2>
            <h3 className='text-3xl py-2 md:text-3xl'>Full Stack Developer</h3>
            <p className='text-2xl py-5 leading-8 text-white mx-w-xl'>I love to make things and solve complex problems. I have over two years of development experience.</p>      
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 md:text-5xl'>
            <a href="https://www.linkedin.com/in/raiyankhalil/"><AiFillLinkedin fill='coral' /></a>
            <a href="https://github.com/RaiyanKhalil"><AiFillGithub fill='coral' /></a>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-4 overflow-hidden'>
            <Image alt='Raiyan Shuvo' src={raiyan} layout="fill" objectFit='cover'/>
          </div>
        </section>
{/* className='list-disc' */}
        <section className='my-4 '>
          <h3 className='text-3xl py-2 my-4 text-center'>Skills</h3>
          <div className='grid grid-cols-3 md:grid-cols-4 gap-1 text-center '>
            <div className='bg-myCoral text-gray-800 px-4 py-2 rounded-md'>HTML</div>
            <div className='bg-myCoral text-gray-800 px-4 py-2 rounded-md'>CSS</div>
            <div className='bg-myCoral text-gray-800 px-4 py-2 rounded-md'>JQuery</div>
            <div className='bg-myCoral text-gray-800 px-4 py-2 rounded-md'>Javascript</div>
            <div className='bg-myCoral text-gray-800 px-4 py-2 rounded-md'>Typescript</div>
            <div className='bg-myCoral text-gray-800 px-4 py-2 rounded-md'>Tailwind</div>
            <div className='bg-myCoral text-gray-800 px-4 py-2 rounded-md'>Bootstrap</div>
            <div className='bg-myCoral text-gray-800 px-4 py-2 rounded-md'>ReactJS</div>
            <div className='bg-myCoral text-gray-800 px-4 py-2 rounded-md'>React-Native</div>
            <div className='bg-myCoral text-gray-800 px-4 py-2 rounded-md'>Python</div>
            <div className='bg-myCoral text-gray-800 px-4 py-2 rounded-md'>Django</div>
            <div className='bg-myCoral text-gray-800 px-4 py-2 rounded-md'>Java</div>
            <div className='bg-myCoral text-gray-800 px-4 py-2 rounded-md'>Spring Boot</div>
            <div className='bg-myCoral text-gray-800 px-4 py-2 rounded-md'>SQL/NoSQL</div>
            <div className='bg-myCoral text-gray-800 px-4 py-2 rounded-md'>Git</div>
            <div className='bg-myCoral text-gray-800 px-4 py-2 rounded-md'>PHP/Laravel</div>
            <div className='bg-myCoral text-gray-800 px-4 py-2 rounded-md'>VueJS</div>
            <div className='bg-myCoral text-gray-800 px-4 py-2 rounded-md'>Express</div>
            <div className='bg-myCoral text-gray-800 px-4 py-2 rounded-md'>Agile</div>
            <div className='bg-myCoral text-gray-800 px-4 py-2 rounded-md'>REST/JSON</div>
            <div className='bg-myCoral text-gray-800 px-4 py-2 rounded-md'>C#</div>
            <div className='bg-myCoral text-gray-800 px-4 py-2 rounded-md'>ASP.NET</div>
            <div className='bg-myCoral text-gray-800 px-4 py-2 rounded-md'>NEXTJS</div>
            <div className='bg-myCoral text-gray-800 px-4 py-2 rounded-md'>AWS/GCP</div>
          </div>
        </section>
        <section className='my-4'>
          <h3 className='text-3xl py-2 text-center my-2'>Professional Experience</h3>
          <div className='min-w-fit mt-5 py-2 leading-loose'>
            <div className='flex justify-between'>              
              <h4>Echologyx Ltd, Dhaka, Bangladesh</h4>
              <h4>June 2021 - January 2022</h4>
            </div>
            <div>
              <h4 className='font-bold'>Software Engineer</h4>
              <h4 className='font-bold'>A/B Test Expert</h4>
              <ul className='list-inside list-disc pl-4'>
                <li>Delivered high-quality, efficient, and robust experimentation code using HTML, SCSS, and JavaScript for A/B testing via experimentation software such as Dynamic Yield, Google Optimize, and VWO.</li>
                <li>Developed home, plp & pdp pages for multiple ecommerce websites.</li>
                <li>Provided web development expertise and insights as a technical consultant on internal and client-facing video calls.</li>
                <li>Contributed feedback and ideas to help scale Cro Metrics' business.</li>
              </ul>
              <h4 className='font-bold'>Product Passport</h4>
              <ul className='list-inside list-disc pl-4'>
                <li>Led full-stack development of the Product Passport application for espare.com, utilizing React Native for mobile development and Strapi.js for backend development.</li>
                <li>Responsible for implementing new features.</li>
                <li>Communicated effectively with project managers, quality assurance analysts, and clients to establish clear expectations and ensure seamless project delivery.</li>
                <li>Application Landing Page: <a className='font-bold italic' href='https://productpassport.co.uk/'>Product Passport</a> </li>
              </ul>
            </div>
          </div>

          <div className='min-w-fit mt-5 py-2 leading-loose'>
            <div className='flex justify-between'>              
              <h4>Dokane Dokane AD, Dhaka, Bangladesh</h4>
              <h4>September 2020 - May 2021</h4>
            </div>
            <div>
              <h4 className='font-bold'>Co-Founder | Software Engineer</h4>
              <ul className='list-inside list-disc pl-4'>
                <li>Spearheaded the development of Bangladesh's first-ever data-driven retail advertising platform.</li>
                <li>Developed the admin application utilizing React, PHP, Laravel, client application using React Native, and AWS EC2 instances to deploy the admin application.</li>
                <li>Ensured seamless incremental development through effective communication, research & development, and project quality assurance.</li>
                <li>Featured in National Paper for innovation in FMCG retail space. <a className='font-bold italic' href="https://www.tbsnews.net/feature/panorama/dokane-dokane-ad-packaging-age-old-marketing-strategy-strokes-tech-180583">The Business Standard</a></li>
              </ul>
            </div>
          </div>

          <div className='min-w-fit mt-5 py-2 leading-loose'>
            <div className='flex justify-between'>              
              <h4>Techdojo, Dhaka, Bangladesh</h4>
              <h4>September 2019 – August 2020</h4>
            </div>
            <div>
              <h4 className='font-bold'>Junior Software Engineer</h4>
              <ul className='list-inside list-disc pl-4'>
                <li>Developed core algorithm for <a href="https://play.google.com/store/apps/details?id=com.reikriya.niyo&hl=en&gl=US">NIYO</a>, a game inspired from <a href="https://apps.apple.com/us/app/letterpress-word-game/id526619424">Letterpress</a> but in Bengali.</li>
                <li>Developed the keyboard UI & functionality for NIYO.</li>
                <li>Responsible for developing the game board & it's functionality of <a href="https://play.google.com/store/apps/details?id=com.reikriya.dui&hl=en&gl=US">DUI</a>, a mashup of <a href="https://play.google.com/store/apps/details?id=com.androbaby.original2048&hl=en&gl=US">2048</a> & <a href="https://play.google.com/store/apps/details?id=com.smilerlee.klondike&hl=en_CA&gl=US">Solitaire.</a></li>
              </ul>
            </div>
          </div>
        </section>
        <section>
          <h3 className='text-3xl py-2 text-center'>Projects</h3>
        
          <div className='grid grid-cols-1 md:grid-cols-3 gap-3'>

            <div class="max-w-md mx-auto bg-myGray rounded-xl shadow-md overflow-hidden md:max-w-2xl">
              <div class="md:flex md:flex-col">
                <div class="md:flex-shrink-0">
                {/* <img class="h-48 w-full object-cover md:h-48 md:w-full" src="https://via.placeholder.com/300" alt="Card image" /> */}
                  {/* <Image src={deved}  /> */}
                </div>
                <div class="p-8">
                  <div class="uppercase tracking-wide text-sm text-gray-300 font-semibold">Web</div>
                  <p class="block mt-1 text-lg leading-tight font-medium text-myCoral">Easy Checkup</p>
                  <p class="mt-2 text-white">A PHP/Laravel application to find doctors near users, based on their location. It will also show a list of relevant doctors in a map based on what type doctors they are searching for. Also has a system for doctors & patients to have virtual sessions.</p>
                  <a href="https://github.com/RaiyanKhalil/easy-check-up" class="mt-4 inline-block px-4 py-2 bg-myCoral text-white font-semibold rounded-lg">Read more</a>
                </div>
              </div>
            </div>


            <div class="max-w-md mx-auto bg-myGray rounded-xl shadow-md overflow-hidden md:max-w-2xl">
              <div class="md:flex md:flex-col">
                <div class="md:flex-shrink-0">
                {/* <img class="h-48 w-full object-cover md:h-48 md:w-full" src="https://via.placeholder.com/300" alt="Card image" /> */}
                  {/* <Image src={deved}  /> */}
                </div>
                <div class="p-8">
                  <div class="uppercase tracking-wide text-sm text-gray-300 font-semibold">Web</div>
                  <p  class="block mt-1 text-lg leading-tight font-medium text-myCoral">Bibliostock</p>
                  <p class="mt-2 text-white">A spring boot application with VueJS as frontend. This application is book management system so mom & pop bookstores can manage their inventory with built in ecommerce platform.</p>
                  <a href="#" class="mt-4 inline-block px-4 py-2 bg-myCoral text-white font-semibold rounded-lg">Read more</a>
                </div>
              </div>
            </div>
            
            <div class="max-w-md mx-auto bg-myGray rounded-xl shadow-md overflow-hidden md:max-w-2xl">
              <div class="md:flex md:flex-col">
                <div class="md:flex-shrink-0">
                {/* <img class="h-48 w-full object-cover md:h-48 md:w-full" src="https://via.placeholder.com/300" alt="Card image" /> */}
                  {/* <Image src={deved}  /> */}
                </div>
                <div class="p-8">
                  <div class="uppercase tracking-wide text-sm text-gray-300 font-semibold">Mobile</div>
                  <p class="block mt-1 text-lg leading-tight font-medium text-myCoral">Lefties</p>
                  <p class="mt-2 text-white">A native android application for restaurants to sell their leftoverr foods at a discounted price to reduce food wastes.</p>
                  <a href="#" class="mt-4 inline-block px-4 py-2 bg-myCoral text-white font-semibold rounded-lg">Read more</a>
                </div>
              </div>
            </div>

            <div class="max-w-md mx-auto bg-myGray rounded-xl shadow-md overflow-hidden md:max-w-2xl">
              <div class="md:flex md:flex-col">
                <div class="md:flex-shrink-0">
                {/* <img class="h-48 w-full object-cover md:h-48 md:w-full" src="https://via.placeholder.com/300" alt="Card image" /> */}
                  {/* <Image src={deved}  /> */}
                </div>
                <div class="p-8">
                  <div class="uppercase tracking-wide text-sm text-gray-300 font-semibold">Mobile</div>
                  <p class="block mt-1 text-lg leading-tight font-medium text-myCoral">Product Passport</p>
                  <p class="mt-2 text-white">An IOS/Android application for "espares.com" to keep track of appliances at home. This applications was developed using React-Native</p>
                  <a href='https://productpassport.co.uk/' class="mt-4 inline-block px-4 py-2 bg-myCoral text-white font-semibold rounded-lg">Read more</a>
                </div>
              </div>
            </div>

            <div class="max-w-md mx-auto bg-myGray rounded-xl shadow-md overflow-hidden md:max-w-2xl">
              <div class="md:flex md:flex-col">
                <div class="md:flex-shrink-0">
                {/* <img class="h-48 w-full object-cover md:h-48 md:w-full" src="https://via.placeholder.com/300" alt="Card image" /> */}
                  {/* <Image src={deved}  /> */}
                </div>
                <div class="p-8">
                  <div class="uppercase tracking-wide text-sm text-gray-300 font-semibold">Mobile</div>
                  <p class="block mt-1 text-lg leading-tight font-medium text-myCoral">Dui</p>
                  <p class="mt-2 text-white">A simple Bangla number game. A brain training game to enhance your Math skills. Start adding similar numbers and become a math Genius!</p>
                  <a href="#" class="mt-4 inline-block px-4 py-2 bg-myCoral text-white font-semibold rounded-lg">Read more</a>
                </div>
              </div>
            </div>
            
            <div class="max-w-md mx-auto bg-myGray rounded-xl shadow-md overflow-hidden md:max-w-2xl">
              <div class="md:flex md:flex-col">
                <div class="md:flex-shrink-0">
                {/* <Image src={niyo} objectFit='cover' height="50%" width="100%" /> */}
                {/* <img class="h-48 w-full object-cover md:h-48 md:w-full" src="" alt="Card image" /> */}
                  {/* <Image src={deved}  /> */}
                </div>
                <div class="p-8">
                  <div class="uppercase tracking-wide text-sm text-gray-300 font-semibold">Mobile</div>
                  <p class="block mt-1 text-lg leading-tight font-medium text-myCoral">Niyo</p>
                  <p class="mt-2 text-white">A unique two-player turn-based game with Bangla words. If you wanted to enhance or show-off your Bangla vocab skills with your friends, this Scrabble-like game with Bangla words is for you!</p>
                  <a href="#" class="mt-4 inline-block px-4 py-2 bg-myCoral text-white font-semibold rounded-lg">Read more</a>
                </div>
              </div>
            </div>
          </div>

        </section> 
      </main>
    </>
  );
};
